# Generated by Django 2.2.4 on 2020-05-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
