# Generated by Django 2.2.4 on 2020-05-17 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='shows',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network', to='shows_app.Show'),
        ),
    ]
