# Generated by Django 2.2.4 on 2020-05-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0005_auto_20200517_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
