# Generated by Django 2.2.4 on 2020-05-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0006_show_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
