# Generated by Django 2.2.4 on 2020-05-18 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0007_show_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='shows',
        ),
        migrations.AddField(
            model_name='show',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='shows_app.Network'),
        ),
    ]
